import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "../../../../lib/db";
import { AdminOrderControls } from "../../AdminOrderControls";

export default async function AdminOrderDetailPage({ params }: { params: Promise<{ orderNumber: string }> }) {
  const { orderNumber } = await params;
  const order = await db.order.findUnique({ where: { orderNumber }, include: { items: true } });
  if (!order) notFound();

  return <section className="rounded-2xl border border-[#E8E6DF] bg-white p-6 shadow-sm">
    <Link href="/admin/orders" className="text-sm font-semibold text-[#5C6B46] underline">← Objednávky</Link>
    <div className="mt-5 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h2 className="text-2xl font-bold text-[#2C2E26]">{order.orderNumber}</h2><p className="mt-1 text-sm text-[#6B6E56]">{order.createdAt.toLocaleString("sk-SK")}</p></div><AdminOrderControls orderNumber={order.orderNumber} status={order.status} paymentStatus={order.paymentStatus} /></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-[#F9F8F6] p-5"><h3 className="mb-3 font-bold">Zákazník a doručenie</h3><p>{[order.customerFirstName, order.customerLastName].filter(Boolean).join(" ") || "—"}</p><p>{order.customerEmail || "—"}</p><p>{order.customerPhone || "—"}</p><p className="mt-3">{[order.shippingStreet, order.shippingZip, order.shippingCity, order.shippingCountry].filter(Boolean).join(", ") || "—"}</p><p className="mt-3 font-semibold">{order.shippingMethodName || order.shippingMethod || "—"}</p>{order.pickupPointCarrier && order.pickupPointName ? <div className="mt-3 rounded-lg border border-[#D5D3C9] bg-white p-3"><p className="font-semibold">{order.pickupPointCarrier}: {order.pickupPointName}</p>{order.pickupPointAddress ? <p className="mt-1 text-sm text-[#6B6E56]">{order.pickupPointAddress}</p> : null}{order.pickupPointId ? <p className="mt-2 text-xs text-[#6B6E56]">ID výdajného miesta: {order.pickupPointId}</p> : null}</div> : null}</section><section className="rounded-xl bg-[#F9F8F6] p-5"><h3 className="mb-3 font-bold">Platba</h3><p>Metóda: {order.paymentMethod}</p><p>Provider: {order.paymentProvider || "—"}</p><p>Stav: {order.paymentStatus}</p><p>Provider stav: {order.externalPaymentStatus || "—"}</p>{order.externalPaymentId ? <p>Comgate transakcia: {order.externalPaymentId}</p> : null}<p>Stav objednávky: {order.status}</p><p>Platená: {order.paidAt?.toLocaleString("sk-SK") || "—"}</p></section></div>
    <section className="mt-6"><h3 className="mb-3 text-lg font-bold">Položky</h3><div className="divide-y divide-[#E8E6DF] rounded-xl border border-[#E8E6DF]">{order.items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 p-4 text-sm"><span>{item.productName} ({item.variantWeight}) × {item.quantity}</span><span>{Number(item.unitPrice).toFixed(2)} {order.currency} / ks</span><strong>{Number(item.totalPrice).toFixed(2)} {order.currency}</strong></div>)}</div><dl className="mt-5 ml-auto grid max-w-sm gap-2 text-sm"><div className="flex justify-between"><dt>Medzisúčet</dt><dd>{Number(order.subtotal).toFixed(2)} {order.currency}</dd></div><div className="flex justify-between"><dt>Zľava</dt><dd>−{Number(order.discount).toFixed(2)} {order.currency}</dd></div><div className="flex justify-between"><dt>Doprava</dt><dd>{Number(order.shippingPrice).toFixed(2)} {order.currency}</dd></div><div className="flex justify-between border-t pt-2 text-base font-bold"><dt>Spolu</dt><dd>{Number(order.total).toFixed(2)} {order.currency}</dd></div></dl></section>
  </section>;
}
